export const FRONTEND_HTML = String.raw`<!doctype html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<meta name="theme-color" content="#05070d">
<meta name="description" content="简洁的 IP 地址与网络信息可视化面板。">
<title>IP 网络信息</title>
<style>
:root{color-scheme:dark;--bg:#05070d;--panel:rgba(10,15,27,.72);--line:rgba(130,160,255,.18);--text:#eef3ff;--muted:#8792aa;--accent:#7c9cff;--accent2:#58e1c1;--danger:#ff6b88;--shadow:0 24px 80px rgba(0,0,0,.42)}
*{box-sizing:border-box}html,body{margin:0;min-height:100%;background:var(--bg);color:var(--text);font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI","Microsoft YaHei",sans-serif}body{overflow-x:hidden}
body:before{content:"";position:fixed;inset:0;z-index:-3;background:radial-gradient(circle at 50% 35%,rgba(67,91,180,.2),transparent 34%),radial-gradient(circle at 15% 85%,rgba(30,160,180,.11),transparent 30%),#05070d}
body:after{content:"";position:fixed;inset:0;z-index:-2;opacity:.35;background-image:linear-gradient(rgba(124,156,255,.045) 1px,transparent 1px),linear-gradient(90deg,rgba(124,156,255,.045) 1px,transparent 1px);background-size:56px 56px;mask-image:linear-gradient(to bottom,transparent,black 20%,black 80%,transparent)}
.orbit{position:fixed;width:620px;height:620px;border:1px solid rgba(124,156,255,.08);border-radius:50%;left:50%;top:43%;transform:translate(-50%,-50%);z-index:-1;box-shadow:0 0 100px rgba(90,110,255,.05),inset 0 0 100px rgba(90,110,255,.035)}.orbit:before,.orbit:after{content:"";position:absolute;border:1px solid rgba(88,225,193,.07);border-radius:50%;inset:70px}.orbit:after{inset:145px;border-color:rgba(124,156,255,.07)}
main{width:min(1040px,calc(100% - 32px));margin:0 auto;padding:clamp(48px,9vh,100px) 0 56px}.hero{text-align:center;margin-bottom:34px}.eyebrow{display:inline-flex;align-items:center;gap:8px;color:var(--muted);font-size:11px;font-weight:700;letter-spacing:.18em}.dot{width:7px;height:7px;border-radius:50%;background:var(--accent2);box-shadow:0 0 14px var(--accent2)}h1{margin:16px 0 9px;font-size:clamp(38px,7vw,72px);line-height:.95;letter-spacing:-.055em;font-weight:760}h1 span{background:linear-gradient(110deg,#fff 15%,#aebfff 55%,#72e7cd);-webkit-background-clip:text;background-clip:text;color:transparent}.sub{margin:0;color:var(--muted);font-size:14px}
.dashboard{display:grid;grid-template-columns:1.2fr .8fr;gap:16px}.panel{position:relative;overflow:hidden;border:1px solid var(--line);background:var(--panel);backdrop-filter:blur(22px);-webkit-backdrop-filter:blur(22px);border-radius:22px;box-shadow:var(--shadow)}.panel:before{content:"";position:absolute;inset:0;background:linear-gradient(135deg,rgba(255,255,255,.055),transparent 30%,transparent 70%,rgba(124,156,255,.035));pointer-events:none}.main-card{padding:30px}.label{color:var(--muted);font-size:11px;letter-spacing:.12em;font-weight:700}.ip{font-variant-numeric:tabular-nums;font-size:clamp(31px,5vw,54px);font-weight:700;letter-spacing:-.04em;margin:10px 0 22px;word-break:break-word}.actions{display:flex;gap:10px}.button{border:1px solid rgba(124,156,255,.28);background:rgba(124,156,255,.08);color:var(--text);padding:11px 15px;border-radius:12px;font:inherit;font-size:13px;font-weight:650;cursor:pointer;transition:.2s}.button:hover{background:rgba(124,156,255,.16);transform:translateY(-1px)}.button.primary{background:linear-gradient(135deg,rgba(124,156,255,.28),rgba(88,225,193,.13));border-color:rgba(124,156,255,.42)}
.stats{display:grid;grid-template-columns:1fr 1fr;gap:1px;background:var(--line)}.stat{min-height:126px;padding:22px;background:rgba(8,12,22,.84)}.value{margin-top:10px;font-size:17px;font-weight:650;line-height:1.35;overflow-wrap:anywhere}.value.muted{color:var(--muted);font-weight:500}.geo-card{padding:26px}.geo-head{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:24px}.status{font-size:10px;color:var(--accent2);border:1px solid rgba(88,225,193,.22);padding:6px 9px;border-radius:999px;letter-spacing:.08em}.rows{display:grid;gap:17px}.row{display:flex;justify-content:space-between;gap:20px;border-bottom:1px solid rgba(130,160,255,.1);padding-bottom:13px}.row:last-child{border-bottom:0}.row b{font-size:13px;text-align:right;font-weight:600}.row .key{color:var(--muted);font-size:12px}.loader{height:2px;background:rgba(124,156,255,.1);overflow:hidden;margin-top:22px}.loader i{display:block;height:100%;width:35%;background:linear-gradient(90deg,transparent,var(--accent),var(--accent2),transparent);animation:load 1.2s infinite}@keyframes load{from{transform:translateX(-160%)}to{transform:translateX(340%)}}.error{color:var(--danger)!important}
.coordinates{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:16px}.coord{padding:13px 14px;border:1px solid rgba(130,160,255,.11);border-radius:12px;background:rgba(255,255,255,.025)}.coord small{display:block;color:var(--muted);font-size:10px;margin-bottom:5px}.coord strong{font-size:13px;font-variant-numeric:tabular-nums}
@media(max-width:760px){main{width:min(100% - 20px,620px);padding-top:38px}.dashboard{grid-template-columns:1fr}.main-card{padding:24px}.geo-card{padding:22px}.stats{grid-template-columns:1fr 1fr}.stat{min-height:108px;padding:18px}.orbit{width:430px;height:430px}}
@media(max-width:420px){.stats{grid-template-columns:1fr}.ip{font-size:34px}.actions .button{flex:1}}
</style>
</head>
<body><div class="orbit"></div><main>
<section class="hero"><div class="eyebrow"><i class="dot"></i>网络信息中心</div><h1><span>我的 IP</span></h1><p class="sub">实时查看您的网络身份与地理信息。</p></section>
<section class="dashboard">
<div class="panel main-card"><div class="label">公网地址</div><div id="ip" class="ip">正在检测…</div><div class="actions"><button id="copy" class="button primary">复制地址</button><button id="refresh" class="button">刷新</button></div><div class="loader"><i></i></div></div>
<div class="panel geo-card"><div class="geo-head"><span class="label">连接信息</span><span id="status" class="status">正在扫描</span></div><div class="rows"><div class="row"><span class="key">国家</span><b id="country">—</b></div><div class="row"><span class="key">地区</span><b id="region">—</b></div><div class="row"><span class="key">城市</span><b id="city">—</b></div><div class="row"><span class="key">网络</span><b id="asn">—</b></div></div><div class="coordinates"><div class="coord"><small>纬度</small><strong id="lat">—</strong></div><div class="coord"><small>经度</small><strong id="lon">—</strong></div></div></div>
</section>
</main>
<script>
const $=id=>document.getElementById(id);let current='';
async function load(){
 $('status').textContent='正在扫描';$('status').classList.remove('error');
 try{const r=await fetch('/geo',{cache:'no-store'});if(!r.ok)throw new Error('Request failed');const d=await r.json();current=d.ip||'';$('ip').textContent=current||'无法获取';$('country').textContent=[d.flag,d.country].filter(Boolean).join(' ')||'—';$('region').textContent=[d.countryRegion,d.region].filter(Boolean).join(' · ')||'—';$('city').textContent=d.city||'—';$('asn').textContent=d.asOrganization||'—';$('lat').textContent=d.latitude??'—';$('lon').textContent=d.longitude??'—';$('status').textContent='连接正常'}catch(e){$('ip').textContent='无法检测';$('ip').classList.add('error');$('status').textContent='连接失败';$('status').classList.add('error')}}
$('copy').onclick=async()=>{if(!current)return;try{await navigator.clipboard.writeText(current);$('copy').textContent='已复制';setTimeout(()=>$('copy').textContent='复制地址',1300)}catch{}};$('refresh').onclick=load;load();
</script></body></html>`
